FROM python:3.12
LABEL authors="qphu1905"

WORKDIR /app
COPY ../.env .
COPY ../requirements.txt .
RUN pip install -r requirements.txt
COPY ./etl_pipeline/transform.py .
CMD ["python", "transform.py"]
